name: Generate PDF List
on: [push]
jobs:
  update-list:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create JSON List
        run: |
          echo "[" > pdf-list.json
          # Updated to look in the 'Pdf' folder
          find Pdf -name "*.pdf" | sed 's/^/"/;s/$/",/' >> pdf-list.json
          # Fixes the last comma
          sed -i '$ s/,$//' pdf-list.json
          echo "]" >> pdf-list.json
      - name: Save to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add pdf-list.json
          git commit -m "Update PDF list from Pdf folder" || echo "No changes"
          git push
